# Generated by Django 3.1.4 on 2020-12-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50)),
                ('target_name', models.CharField(max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='api.dataset')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_type', to='api.artifacttype')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_type', to='api.artifacttype')),
            ],
            options={
                'ordering': ['dataset', 'source_name', 'target_name'],
                'unique_together': {('dataset', 'source_type', 'source_name', 'target_type', 'target_name')},
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.dataset')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='api.artifacttype')),
            ],
            options={
                'ordering': ['dataset', 'type', 'name'],
                'unique_together': {('dataset', 'type', 'name')},
            },
        ),
    ]
